export default {
    FETCH_IMAGES: 'FETCH_IMAGES',
    FETCH_SPECIFIC_IMAGES: 'FETCH_SPECIFIC_IMAGES',
    FETCH_USER_IMAGES: 'FETCH_USER_IMAGES',
    DELETE_IMAGE: 'DELETE_IMAGE',
    SET_MODAL_IMAGE: 'SET_MODAL_IMAGE',
    UPDATE_IMAGE: 'UPDATE_IMAGE',
    LIKE_IMAGE: 'LIKE_IMAGE'
} 